Auto-Commit at : Sun May 18 10:15:11 AM MDT 2025

diff --git a/config/crontab/setup b/config/crontab/setup
--- a/config/crontab/setup
+++ b/config/crontab/setup
@@ -4,6 +4,14 @@
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 
 # make sure crontab is installed
+if ! command -v crontab &> /dev/null
+then
+    echo "crontab could not be found, please install it first"
+    exit
+fi
+
+# install file from this directory to crontab
+cat $DIR/monkey | crontab -u $USER -
 
 
 
