Auto-Commit at : Sun Aug 27 06:47:38 PM MDT 2023

diff --git a/scripts/cal b/scripts/cal
--- a/scripts/cal
+++ b/scripts/cal
@@ -1,8 +1,15 @@
 #!/usr/bin/bash
 # ---------------------------------- the code ----------------------------------
+
+check_khal() {
+    if ! command -v khal &> /dev/null; then
+        echo "khal not found"
+        exit
+    fi
+}
+
 today() {
-    find "$SNIPPETS" -maxdepth 2 -mindepth 2 -not -path "*/.*" \
-    | rev | cut -d '/' -f 1-2 | rev 
+    khal list --format '{cyan-bold}{start-end-time-style} {calendar-color}{title}{repeat-symbol}' --day-format '{yellow}{name}, {date}' --exclude-calendar 'Pattern Updates' --exclude-calendar 'Sneha'
 }
 
 usage() {
