Auto-Commit at : Mon May 26 05:03:23 PM MDT 2025

diff --git a/scripts/cron-wrapper b/scripts/cron-wrapper
--- a/scripts/cron-wrapper
+++ b/scripts/cron-wrapper
@@ -13,11 +13,10 @@ while IFS= read -r line; do
 done < /home/monkey/.bashrc
 
 
-# run the command with the specified user and environment variables
 # if the command fails echo an error message and exit with status 1
 command="$@"
-if ! su -c "$command" monkey; then
-    echo "Error: Command '$command' failed to execute as user 'monkey'."
+if ! eval "$command"; then
+    echo "Error: Command '$command' failed to execute."
     exit 1
 fi
 
